### ISSUE TITLE
bat file

### ISSUE THREAD

**Issue by seadogro** [m-lyon/filter-subs#11]
I have a bat file for your program which makes it available to just drag and select as many subtitles as you want and drag into the bat file and it will remove sdh of all subtitles at once.

Please add the bat file as well.
Code for bat is this:
@echo off

if [%1]==[] goto :eof
:loop
filter-subtitles.py -s %1
shift
if not [%1]==[] goto loop

**Comment by m-lyon** [comment]
Thank you for the suggestion, though I don't think including a `bat` file is within the scope of this project as 1) it is Windows specific, which this project is not, and 2) providing code on how to use `subtitle-filter` within a scripting language like `bat` or `bash` is a bit superfluous.
