### ISSUE TITLE
Add bat file

### ISSUE THREAD

**Issue by seadogro** [m-lyon/filter-subs#15]
Hi thank you so much for your nice too. I love it. As suggestion ...you could add bat script for easier use of your tool.

code for bat:
@echo off

if [%1]==[] goto :eof
:loop
filter-subtitles.py -s %1
shift
if not [%1]==[] goto loop

In this way you only need the bat file and can drag multiple subtitles in the bat file and it will auto remove the sdh in it. 
(Only thing needed is that python is runable via cmd command, linked with cmd).
Makes it way more comfortable especially if you have multiple files where you want sdh removed. Also easier for newbies in python.

**Comment by m-lyon** [comment]
batch scripts, as well as other scripting languages like `bash` or `zsh` are out of scope for this project.
