### ISSUE TITLE
not removing all sdh

### ISSUE THREAD

**Issue by seadogro** [m-lyon/filter-subs#20]
Hi, please add that it removes
sdh like "all:" as well.

Example subtitle where it does not remove "all:" 
The Rookie 
https://www.opensubtitles.org/en/subtitles/9913490/the-rookie-episode-6-2-en

sometimes it also not removes big names in letters such as WOLF: etc.

Please fix,thanks.

**Comment by m-lyon** [comment]
Fixed, update to latest version: `v1.4.9`.

**Comment by seadogro** [comment]
Thank you 👍
