### ISSUE TITLE
not removing some SDH

### ISSUE THREAD

**Issue by seadogro** [m-lyon/filter-subs#22]
Hi, it not removing all SDH from the subtitle SWAT.
https://www.opensubtitles.org/en/subtitles/10003627/s-w-a-t-snafu-en

Before is:
768
00:32:06,925 --> 00:32:09,057
HONDO [over comm]:
What do you got for me, Cabrera?

769
00:32:09,057 --> 00:32:10,450
Still looking, Hondo.

770
00:32:10,450 --> 00:32:13,105
All right, let's move! Now!

771
00:32:14,628 --> 00:32:15,716
[gunshot]

772
00:32:15,716 --> 00:32:17,936
TAN:
Fall back, fall back. Get down!

773
00:32:17,936 --> 00:32:19,763
25-David, we're taking fire.

774
00:32:19,763 --> 00:32:22,592
Powell and Alfaro, keep moving
- with those Hammers!
- Roger.

775
00:32:24,246 --> 00:32:27,597
ELIJAH [over comm]:
Hector? Hector?

After is:
725
00:32:06,925 --> 00:32:09,057
HONDO
What do you got for me, Cabrera?

726
00:32:09,057 --> 00:32:10,450
Still looking, Hondo.

727
00:32:10,450 --> 00:32:13,105
All right, let's move! Now!

728
00:32:15,716 --> 00:32:17,936
Fall back, fall back. Get down!

729
00:32:17,936 --> 00:32:19,763
25-David, we're taking fire.

730
00:32:19,763 --> 00:32:22,592
Powell and Alfaro, keep moving
- with those Hammers!
- Roger.

731
00:32:24,246 --> 00:32:27,597
ELIJAH
Hector? Hector?

It does not removed 00:32:06,925   HONDO [over comm]: and also not ELIJAH at 00:32:24,246

Please fix it if possible.

Thank you.

**Comment by m-lyon** [comment]
This isn't possible to fix because you would need to filter out fully capitalised lines, which would introduce too many false positives and be too destructive a filter.

**Comment by seadogro** [comment]
> This isn't possible to fix because you would need to filter out fully capitalised lines, which would introduce too many false positives and be too destructive a filter.

Okay thanks for the info.
Though is it possible to add the function to
Remove text between asterisks * ... * ?
Like as example 
* wind blowing*. That it completely deletes the asterisks and the words in it ?

**Comment by m-lyon** [comment]
Yes, i've added this now on version `v1.4.10`

**Comment by seadogro** [comment]
> Yes, i've added this now on version `v1.4.10`

Thanks :)
